name: "Conventional Commit Validation PR Title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR Title For Conventional Commit
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # v5.2.0
      - uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54